name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: "v1.x"

      - name: Check Formatting
        run: deno fmt --check --config deno.jsonc

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: "v1.x"

      - name: Lint
        run: deno lint --config deno.jsonc

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: "v1.x"

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build libsecp256k1
        run: |
          cd secp256k1
          ./autogen.sh
          ./configure --enable-module-schnorrsig --enable-module-recovery --enable-tests=no
          make

      - name: Run Tests
        env:
          DENO_SECP256K1_PATH: secp256k1/.libs/libsecp256k1.so
        run: deno test --unstable --allow-env --allow-ffi
