name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: "v2.x"

      - name: Check Formatting
        run: deno fmt --check --config deno.jsonc

      - name: Lint
        run: deno lint --config deno.jsonc

      - name: Build libsecp256k1
        run: |
          cd secp256k1
          ./autogen.sh
          ./configure --enable-module-schnorrsig --enable-module-recovery --enable-tests=no --enable-benchmark=no
          make

      - name: Run Tests
        env:
          DENO_SECP256K1_PATH: secp256k1/.libs/libsecp256k1.so
        run: deno test --unstable-ffi --allow-env=DENO_SECP256K1_PATH --allow-ffi
